Prog_Lang=['Java','python', 'c','c++','SQL']
print(Prog_Lang)
print(type(Prog_Lang))
print("accessing the eloements using +ve indexing")
print(Prog_Lang[0])
print(Prog_Lang[1])
print(Prog_Lang[2])
print(Prog_Lang[3])
print(Prog_Lang[4])
print("accessing the eloements using -ve indexing")
print(Prog_Lang[-5])
print(Prog_Lang[-4])
print(Prog_Lang[-3])
print(Prog_Lang[-2])
print(Prog_Lang[-1])